<?php
set('profile_id', 'ms-krishnan');
set('profile_name', 'M.S. Krishnan');
set('profile_title', 'Accenture Professor of Computer and Information Systems; Faculty Director of India Initiatives; Professor of Technology and Operations, Stephen M. Ross School of Business');
set('profile_content', <<<HTML
	<p>Dr. M. S. Krishnan (“Krishnan”) is the Accenture Professor of Computer Information Systems and Professor of Technology and Operations at the Ross School of Business, University of Michigan. He is also the Faculty Director for India Initiatives at the Ross School of Business. He has co-authored the book “The New Age of Innovation: Driving Co-Created Value with Global Networks” with Professor C. K. Prahalad (late). The Economist and BusinessWeek magazine named this book as one of the Best Books on Innovation in 2008. Dr. Krishnan received his degrees in Mathematics and Computer Applications from the University of Delhi, India and Ph.D. in Information Systems from Carnegie Mellon University, Pittsburgh, USA. He was awarded the ICIS Best Dissertation Prize for his Doctoral Thesis on “Cost and Quality Considerations in Software Product Management”. His research interest includes Business Innovation, Corporate IT Strategy, Business Value of IT investments, Metrics and Measures for Business Process and Software Quality, Productivity and Customer satisfaction. In January 2000, American Society for Quality (ASQ) selected him as one of the 21 voices of quality for the twenty first century. In 2004, he was selected as one of the top thinkers on Business Technology by Informationweek-Optimze magazines based on their reader surveys. His research articles and writings have appeared in several journals including Management Science, Information Systems Research, Management Information Systems Quarterly, Strategic Management Journal, IEEE Transactions on Software Engineering, IEEE Software, Decision Support Systems, Harvard Business Review, The Wall Street Journal, Financial Times, Information Week, Sloan Management Review, Optimize and Communications of the ACM. His article “The role of team factors in software cost and quality” was awarded the 1999 ANBAR Electronic Citation of Excellence. Dr. Krishnan has consulted with Ford Motor Company, NCR, IBM, Nestle, ICICI, TVS Group, NBC, Next Services, Infosys, Techvoyant, Goorulearning and Ramco Systems. He also serves on the board of advisors of companies.</p>
HTML
);
?>
{{>template/panelist-info}}